"""Flask adapter smoke tests."""

import datetime
import html
from io import BytesIO
from pathlib import Path
from types import SimpleNamespace

import astropy.units as u
import numpy as np
import pytest

from surfs_up.web import create_app


def test_preview_uses_shared_generator():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "iswa_map_date": "2026-07-07T09:30:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    )

    assert response.status_code == 200
    assert b"Generated by SURFs_UP shared core" in response.data
    assert b'id="generated-code-dialog"' in response.data


def test_preview_supports_wsa_iswa():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "wsa_iswa",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "decelerate": "on",
        },
    )

    assert response.status_code == 200
    assert b"get_WSA_from_ISWA" in response.data


def test_preview_uses_model_start_for_wsa_iswa_map_time_when_checked():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "wsa_iswa",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "iswa_map_date": "2026-07-07T09:30:00",
            "iswa_use_model_start": "on",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    )

    body = html.unescape(response.get_data(as_text=True))
    assert response.status_code == 200
    assert "iswa_map_time = datetime.datetime.fromisoformat('2026-07-03T12:00:00')" in body
    assert "2026-07-07T09:30:00" not in body


def test_preview_passes_advanced_model_grid_settings():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "user_specified",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "dr_rs": "2.5",
            "nlon": "64",
            "vmax_kms": "2500",
        },
    )

    assert response.status_code == 200
    assert b"dr=2.5 * u.solRad" in response.data
    assert b"nlon=64" in response.data
    assert b"v_max=2500.0" in response.data


def test_page_exposes_run_gated_workflow_and_configuration_controls():
    response = create_app({"TESTING": True}).test_client().get("/")

    assert response.status_code == 200
    assert b'data-tab="model"' in response.data
    assert b'data-tab="ambient"' in response.data
    assert b'data-tab="cme"' in response.data
    assert b'id="load-configuration"' in response.data
    assert b'id="save-configuration"' in response.data
    assert b"Show Terminal Output" in response.data
    assert b'id="show-terminal-output"' in response.data
    assert b'id="run-surf-button"' in response.data
    assert b'id="iswa-map-date"' in response.data
    assert b'name="iswa_use_model_start" id="iswa-use-model-start" type="checkbox" checked' in response.data
    assert b"busy-button" in response.data
    assert b"Grabbing and processing input data" in response.data
    assert b"/run-progress/" in response.data
    assert b"Configuration changed. Run SURF again." in response.data
    assert b"Model Parameters" in response.data
    assert b"Advanced" in response.data
    assert b"Open manual CME editor" in response.data
    assert b"Remove Selected" in response.data
    assert b'id="cme-editor"' in response.data
    assert b"id=\"load-donki\"" in response.data
    assert b"Cone CME lists" in response.data
    assert b'name="grab_donki_at_run_start"' in response.data
    assert b"Grab the DONKI CMEs now" in response.data
    assert b"Load a user-supplied Cone CME list" in response.data
    assert b"SURF's UP" in response.data
    assert b"Space-weather Utilities for Research and Forecasting" in response.data
    assert b"Solar wind modelling via" not in response.data
    assert b"Model start date (default: 5 days prior to forecast date, to allow CME propagation)" in response.data
    assert b"Include B polarity" in response.data
    assert b"Include bpol in run" not in response.data
    assert b'name="simtime_days" type="number" step="0.1" value="10"' in response.data
    assert b'id="edit-selected-cme"' in response.data
    assert b'name="track_cmes" type="checkbox"' in response.data
    assert b'name="track_cmes" type="checkbox" checked' not in response.data
    assert b'<option value="forecast">Forecast</option>' in response.data
    assert b"Reconstruction (requires 27 days of data after run end time)" in response.data
    assert b"Cone CME lists (typically for model inner boundary at 0.1 AU)" in response.data
    assert b"Configure, run and explore SURF simulations" not in response.data
    assert b'name="wsa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="iswa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="mas_use_map_time"' in response.data
    assert b'name="wsa_use_map_time"' in response.data
    assert b'name="cortom_use_map_time"' in response.data


def test_template_turns_off_donki_for_omni_outward_selection():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert "disableDonkiForOutwardOmni" in template
    assert 'source === "omni"' in template
    assert "grabDonkiAtRunStart.checked = false" in template


def test_template_uses_clearer_top_tabs_without_duplicate_panel_headings():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert ">Set inner boundary to 215 Rs</span>" in template
    assert ">Outward propagation</span>" not in template
    assert ">Model parameters</h2>" not in template
    assert ">Ambient solar wind</h2>" not in template
    assert '<h2 class="wide">CMEs</h2>' not in template
    assert '<h2 class="mt-0">Plots</h2>' not in template
    assert "These products remain available while this server process retains the run." not in template
    assert '<h2 class="mt-0">Movies</h2>' not in template
    assert "text-base font-semibold" in template
    assert "hover:border-cyan-200" in template


def test_template_hides_post_run_tabs_when_run_becomes_stale():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert "function hidePostRunTabs()" in template
    assert '["plots", "movies"].forEach' in template
    assert 'document.querySelector(`[data-tab="${name}"]`)?.classList.add("hidden")' in template
    assert 'document.getElementById("post-run-tab-spacer")?.classList.add("hidden")' in template
    assert 'if (["plots", "movies"].includes(activeTab))' in template
    assert 'activateTab("model")' in template
    assert "hidePostRunTabs();" in template


def test_run_start_donki_cmes_are_returned_to_populate_cme_tab(monkeypatch):
    import surfs_up.web.app as web_app

    donki_cme = {
        "longitude": 10.0,
        "latitude": 2.0,
        "speed": 900.0,
        "width": 45.0,
        "t_launch_day": 0.25,
        "t_launch_datetime": "2026-07-03 18:00:00",
        "thickness_rs": 0,
        "initial_height_rs": 21.5,
        "cme_expansion": False,
        "cme_fixed_duration": True,
        "fixed_duration_hr": 12,
        "profile_type": "square",
        "plasma_mode": "Fraction of ambient",
        "density_fraction": 1,
        "temperature_fraction": 1,
        "cme_density_pcc": 100,
        "cme_temperature_k": 100000,
        "source": "donki",
        "donki_id": "2026-test-donki",
    }
    monkeypatch.setattr(web_app, "_fetch_donki_cmes", lambda *_args: [donki_cme])
    monkeypatch.setattr(web_app, "build_generated_code", lambda _simulation: "# code")
    monkeypatch.setattr(
        web_app,
        "run_generated_code",
        lambda *_args, **_kwargs: SimpleNamespace(
            success=True,
            model=object(),
            message="Run completed",
            output="",
        ),
    )
    monkeypatch.setattr(web_app, "_retain_model", lambda *_args: "run123")
    monkeypatch.setattr(
        web_app,
        "_model_defaults",
        lambda: {
            "default_start": "2026-07-03T12:00:00",
            "default_iswa_map_datetime": "2026-07-03T12:00",
            "default_cr_num": 2300,
            "default_cr_lon": 0.0,
            "default_latitude": 0.0,
        },
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/",
        data={
            "action": "run",
            "ambient_source": "wsa_iswa",
            "grab_donki_at_run_start": "on",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "cmes_json": '[{"source":"manual","longitude":0,"latitude":0,"speed":800,'
            '"width":60,"t_launch_day":0.5}]',
        },
    )

    assert response.status_code == 200
    assert b"const submittedCmes =" in response.data
    assert b"2026-test-donki" in response.data
    assert b"Loaded ${submittedCmes.filter" in response.data


def test_omni_outward_run_does_not_auto_fetch_donki(monkeypatch):
    import surfs_up.web.app as web_app

    def fail_fetch(*_args, **_kwargs):
        raise AssertionError("DONKI should not be fetched for OMNI outward runs")

    monkeypatch.setattr(web_app, "_fetch_donki_cmes", fail_fetch)
    app = create_app({"TESTING": True})

    with app.test_request_context(
        "/",
        method="POST",
        data={
            "action": "run",
            "ambient_source": "omni",
            "use_215_inner_boundary": "on",
            "grab_donki_at_run_start": "on",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    ):
        simulation = web_app._request_from_form()

    assert simulation.ambient["source"] == "omni"
    assert simulation.cmes == []


def test_model_coordinate_endpoint_returns_synchronised_values():
    response = create_app({"TESTING": True}).test_client().get(
        "/model-coordinates?datetime=2026-07-03T12:00:00"
    )

    assert response.status_code == 200
    payload = response.get_json()
    assert payload["datetime"] == "2026-07-03T12:00:00"
    assert isinstance(payload["cr_num"], int)
    assert -90 <= payload["earth_latitude"] <= 90


def test_ambient_file_time_endpoint_returns_inferred_timestamp(monkeypatch):
    import surfs_up.web.app as web_app

    expected = datetime.datetime(2026, 7, 3, 12, 0, 0)
    monkeypatch.setattr(web_app, "_ambient_file_start_time", lambda source, path: expected)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-file-time",
        data={
            "source": "wsa",
            "file": (BytesIO(b"test data"), "sample.fits"),
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.get_json()["datetime"] == "2026-07-03T12:00:00"


@pytest.mark.parametrize(
    "source,data,filename",
    [
        (
            "mas",
            {
                "ambient_source": "mas",
                "latitude": "0",
                "mas_cr_num": "2000",
                "mas_decelerate": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "wsa",
            {
                "ambient_source": "wsa",
                "latitude": "0",
                "wsa_decelerate": "on",
                "wsa_speed_reduction": "on",
                "include_bpol": "on",
            },
            "sample.fits",
        ),
        (
            "wsa_iswa",
            {
                "ambient_source": "wsa_iswa",
                "latitude": "0",
                "iswa_map_date": "2026-07-03T12:30:00",
                "iswa_decelerate": "on",
                "iswa_speed_reduction": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "cortom",
            {
                "ambient_source": "cortom",
                "latitude": "0",
                "cortom_decelerate": "on",
                "include_bpol": "on",
            },
            "sample.dat",
        ),
    ],
)
def test_ambient_preview_endpoint_returns_png_for_requested_sources(monkeypatch, tmp_path, source, data, filename):
    import surf.surf_inputs as sin

    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s
    b_profile = np.linspace(1, 4, 4)

    monkeypatch.setattr(sin, "get_MAS_vr_map", lambda cr_num: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_MAS_long_profile", lambda cr_num, latitude: profile)
    monkeypatch.setattr(sin, "get_MAS_br_long_profile", lambda cr_num, latitude: b_profile)
    monkeypatch.setattr(
        sin,
        "map_v_boundary_inwards",
        lambda v_orig, source_radius, inner_radius, b_orig=None, **kwargs: (
            (v_orig * 0.8, np.asarray(b_orig) * 0.7) if b_orig is not None else v_orig * 0.8
        ),
    )
    monkeypatch.setattr(
        sin,
        "map_v_inwards",
        lambda v_orig, source_radius, longitude, inner_radius: (v_orig * 0.9, None, None, None),
    )
    monkeypatch.setattr(
        sin,
        "get_WSA_maps",
        lambda path: (speed_map, longitudes, latitudes),
    )
    monkeypatch.setattr(sin, "get_WSA_long_profile", lambda path, latitude: profile)
    monkeypatch.setattr(sin, "get_WSA_br_long_profile", lambda path, latitude: b_profile)
    monkeypatch.setattr(sin, "get_WSA_from_ISWA", lambda required_for: str(tmp_path / "iswa.fits"))
    monkeypatch.setattr(sin, "get_CorTom_vr_map", lambda path: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_CorTom_long_profile", lambda path, latitude: profile)

    if source == "wsa_iswa":
        (tmp_path / "iswa.fits").write_bytes(b"fits")

    request_data = dict(data)
    if filename is not None:
        request_data[f"{source}_file"] = (BytesIO(b"test data"), filename)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data=request_data,
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.mimetype == "image/png"


def test_ambient_preview_uses_parker_wsa_reduction_for_non_huxt(monkeypatch):
    import surf.surf_inputs as sin

    calls = []
    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s

    monkeypatch.setattr(sin, "get_WSA_maps", lambda path: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_WSA_long_profile", lambda path, latitude: profile)
    monkeypatch.setattr(sin, "get_WSA_br_long_profile", lambda path, latitude: np.ones(4))
    monkeypatch.setattr(sin, "map_v_boundary_inwards", lambda v_orig, *args, **kwargs: v_orig)
    monkeypatch.setattr(
        sin,
        "map_v_inwards",
        lambda v_orig, source_radius, longitude, inner_radius: calls.append("huxt") or (v_orig, None, None, None),
    )
    monkeypatch.setattr(
        sin,
        "map_v_inwards_parker",
        lambda v_orig, source_radius, longitude, inner_radius: calls.append("parker") or (v_orig, None, None, None),
        raising=False,
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data={
            "solver": "hydro",
            "ambient_source": "wsa",
            "latitude": "0",
            "wsa_decelerate": "on",
            "wsa_speed_reduction": "on",
            "wsa_file": (BytesIO(b"test data"), "sample.fits"),
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert calls == ["parker"]


def test_ambient_preview_passes_parker_acc_profile_for_non_huxt_boundary_mapping(monkeypatch):
    import surf.surf_inputs as sin

    acc_profiles = []
    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s

    monkeypatch.setattr(sin, "get_MAS_vr_map", lambda cr_num: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_MAS_long_profile", lambda cr_num, latitude: profile)
    monkeypatch.setattr(
        sin,
        "map_v_boundary_inwards",
        lambda v_orig, *args, **kwargs: acc_profiles.append(kwargs.get("acc_profile")) or v_orig,
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data={
            "solver": "hydro",
            "ambient_source": "mas",
            "latitude": "0",
            "mas_cr_num": "2000",
            "mas_decelerate": "on",
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert acc_profiles == ["parker"]
