"""Flask adapter smoke tests."""

import datetime
from io import BytesIO

import astropy.units as u
import numpy as np
import pytest

from surfs_up.web import create_app


def test_preview_uses_shared_generator():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "iswa_map_date": "2026-07-07T09:30:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    )

    assert response.status_code == 200
    assert b"Generated by SURFs_UP shared core" in response.data
    assert b'id="generated-code-dialog"' in response.data


def test_preview_supports_wsa_iswa():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "wsa_iswa",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "decelerate": "on",
        },
    )

    assert response.status_code == 200
    assert b"get_WSA_from_ISWA" in response.data


def test_preview_passes_advanced_model_grid_settings():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "user_specified",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "dr_rs": "2.5",
            "nlon": "64",
            "vmax_kms": "2500",
        },
    )

    assert response.status_code == 200
    assert b"dr=2.5 * u.solRad" in response.data
    assert b"nlon=64" in response.data
    assert b"v_max=2500.0" in response.data


def test_page_exposes_run_gated_workflow_and_configuration_controls():
    response = create_app({"TESTING": True}).test_client().get("/")

    assert response.status_code == 200
    assert b'data-tab="model"' in response.data
    assert b'data-tab="ambient"' in response.data
    assert b'data-tab="cme"' in response.data
    assert b'id="load-configuration"' in response.data
    assert b'id="save-configuration"' in response.data
    assert b"Show Terminal Output" in response.data
    assert b'id="show-terminal-output"' in response.data
    assert b'id="run-surf-button"' in response.data
    assert b"busy-button" in response.data
    assert b"Grabbing and processing input data" in response.data
    assert b"/run-progress/" in response.data
    assert b"Configuration changed. Run SURF again." in response.data
    assert b"Model Parameters" in response.data
    assert b"Advanced" in response.data
    assert b"Open manual CME editor" in response.data
    assert b"Remove Selected" in response.data
    assert b'id="cme-editor"' in response.data
    assert b"id=\"load-donki\"" in response.data
    assert b"Cone CME lists" in response.data
    assert b'name="grab_donki_at_run_start"' in response.data
    assert b"Grab the DONKI CMEs now" in response.data
    assert b"Load a user-supplied Cone CME list" in response.data
    assert b"SURF's UP" in response.data
    assert b"Space-weather Utilities for Research and Forecasting" in response.data
    assert b'name="simtime_days" type="number" step="0.1" value="10"' in response.data
    assert b'id="edit-selected-cme"' in response.data
    assert b'name="track_cmes" type="checkbox"' in response.data
    assert b'name="track_cmes" type="checkbox" checked' not in response.data
    assert b'<option value="forecast">Forecast</option>' in response.data
    assert b"Reconstruction (requires 27days of data after run end time)" in response.data
    assert b"Cone CME lists (typically for model inner boundary at 0.1 AU)" in response.data
    assert b"Configure, run and explore SURF simulations" not in response.data
    assert b'name="wsa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="iswa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="mas_use_map_time"' in response.data
    assert b'name="wsa_use_map_time"' in response.data
    assert b'name="cortom_use_map_time"' in response.data


def test_model_coordinate_endpoint_returns_synchronised_values():
    response = create_app({"TESTING": True}).test_client().get(
        "/model-coordinates?datetime=2026-07-03T12:00:00"
    )

    assert response.status_code == 200
    payload = response.get_json()
    assert payload["datetime"] == "2026-07-03T12:00:00"
    assert isinstance(payload["cr_num"], int)
    assert -90 <= payload["earth_latitude"] <= 90


def test_ambient_file_time_endpoint_returns_inferred_timestamp(monkeypatch):
    import surfs_up.web.app as web_app

    expected = datetime.datetime(2026, 7, 3, 12, 0, 0)
    monkeypatch.setattr(web_app, "_ambient_file_start_time", lambda source, path: expected)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-file-time",
        data={
            "source": "wsa",
            "file": (BytesIO(b"test data"), "sample.fits"),
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.get_json()["datetime"] == "2026-07-03T12:00:00"


@pytest.mark.parametrize(
    "source,data,filename",
    [
        (
            "mas",
            {
                "ambient_source": "mas",
                "latitude": "0",
                "mas_cr_num": "2000",
                "mas_decelerate": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "wsa",
            {
                "ambient_source": "wsa",
                "latitude": "0",
                "wsa_decelerate": "on",
                "wsa_speed_reduction": "on",
                "include_bpol": "on",
            },
            "sample.fits",
        ),
        (
            "wsa_iswa",
            {
                "ambient_source": "wsa_iswa",
                "latitude": "0",
                "iswa_map_date": "2026-07-03T12:30:00",
                "iswa_decelerate": "on",
                "iswa_speed_reduction": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "cortom",
            {
                "ambient_source": "cortom",
                "latitude": "0",
                "cortom_decelerate": "on",
                "include_bpol": "on",
            },
            "sample.dat",
        ),
    ],
)
def test_ambient_preview_endpoint_returns_png_for_requested_sources(monkeypatch, tmp_path, source, data, filename):
    import surf.surf_inputs as sin

    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s
    b_profile = np.linspace(1, 4, 4)

    monkeypatch.setattr(sin, "get_MAS_vr_map", lambda cr_num: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_MAS_long_profile", lambda cr_num, latitude: profile)
    monkeypatch.setattr(sin, "get_MAS_br_long_profile", lambda cr_num, latitude: b_profile)
    monkeypatch.setattr(
        sin,
        "map_v_boundary_inwards",
        lambda v_orig, source_radius, inner_radius, b_orig=None: (
            (v_orig * 0.8, np.asarray(b_orig) * 0.7) if b_orig is not None else v_orig * 0.8
        ),
    )
    monkeypatch.setattr(
        sin,
        "map_v_inwards",
        lambda v_orig, source_radius, longitude, inner_radius: (v_orig * 0.9, None),
    )
    monkeypatch.setattr(
        sin,
        "get_WSA_maps",
        lambda path: (speed_map, longitudes, latitudes),
    )
    monkeypatch.setattr(sin, "get_WSA_long_profile", lambda path, latitude: profile)
    monkeypatch.setattr(sin, "get_WSA_br_long_profile", lambda path, latitude: b_profile)
    monkeypatch.setattr(sin, "get_WSA_from_ISWA", lambda required_for: str(tmp_path / "iswa.fits"))
    monkeypatch.setattr(sin, "get_CorTom_vr_map", lambda path: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_CorTom_long_profile", lambda path, latitude: profile)

    if source == "wsa_iswa":
        (tmp_path / "iswa.fits").write_bytes(b"fits")

    request_data = dict(data)
    if filename is not None:
        request_data[f"{source}_file"] = (BytesIO(b"test data"), filename)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data=request_data,
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.mimetype == "image/png"
