"""Flask adapter smoke tests."""

import datetime
import html
import json
from io import BytesIO
from pathlib import Path
from types import SimpleNamespace

import astropy.units as u
import numpy as np
import pytest
from flask import session
from werkzeug.exceptions import NotFound

from surfs_up.web import create_app


def test_browser_sessions_isolate_uploads_runs_and_progress():
    import surfs_up.web.app as web_app

    app = create_app({"TESTING": True, "SECRET_KEY": "test-session-secret"})
    run_id = "isolatedrun"

    with app.test_request_context("/"):
        session["surf_session_id"] = "user-a"
        web_app._RUNS[run_id] = {
            "model": object(),
            "simulation": None,
            "owner_session_id": "user-a",
        }
        web_app._set_run_progress("progress", "Running A")
        assert web_app._run_for(run_id)["owner_session_id"] == "user-a"

    with app.test_request_context("/"):
        session["surf_session_id"] = "user-b"
        with pytest.raises(NotFound):
            web_app._run_for(run_id)
        assert web_app._RUN_PROGRESS.get("user-b:progress", "") == ""

    app_source = Path("surfs_up/web/app.py").read_text(encoding="utf-8")
    assert 'Path(tempfile.gettempdir()) / "surfs_up_uploads" / _session_id()' in app_source
    assert 'path = upload_dir / f"{uuid.uuid4().hex}{suffix}"' in app_source
    web_app._RUNS.pop(run_id, None)
    web_app._RUN_PROGRESS.pop("user-a:progress", None)


def test_preview_uses_shared_generator():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "iswa_map_date": "2026-07-07T09:30:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    )

    assert response.status_code == 200
    assert b"Generated by SURFs_UP shared core" in response.data
    assert b'id="generated-code-dialog"' in response.data


def test_preview_supports_wsa_iswa():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "wsa_iswa",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "decelerate": "on",
        },
    )

    assert response.status_code == 200
    assert b"get_WSA_from_ISWA" in response.data


def test_preview_uses_iswa_map_time_minus_five_days_as_model_start_when_checked():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "wsa_iswa",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "iswa_map_date": "2026-07-07T09:30:00",
            "iswa_use_model_start": "on",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    )

    body = html.unescape(response.get_data(as_text=True))
    assert response.status_code == 200
    assert "start_time = datetime.datetime.fromisoformat('2026-07-02 09:30:00')" in body
    assert "iswa_map_time = datetime.datetime.fromisoformat('2026-07-07T09:30:00')" in body


def test_preview_passes_advanced_model_grid_settings():
    client = create_app({"TESTING": True}).test_client()
    response = client.post(
        "/",
        data={
            "action": "preview",
            "solver": "huxt",
            "ambient_source": "user_specified",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "dr_rs": "2.5",
            "nlon": "64",
            "vmax_kms": "2500",
        },
    )

    assert response.status_code == 200
    assert b"dr=2.5 * u.solRad" in response.data
    assert b"nlon=64" in response.data
    assert b"v_max=2500.0" in response.data


def test_page_exposes_run_gated_workflow_and_configuration_controls():
    response = create_app({"TESTING": True}).test_client().get("/")

    assert response.status_code == 200
    assert b'data-tab="model"' in response.data
    assert b'data-tab="ambient"' in response.data
    assert b'data-tab="cme"' in response.data
    assert b'data-tab="outputs"' in response.data
    assert b'id="load-configuration"' in response.data
    assert b'id="save-configuration"' in response.data
    assert b"Show Terminal Output" in response.data
    assert b'id="show-terminal-output"' in response.data
    assert b'id="run-surf-button"' in response.data
    assert b'id="iswa-map-date"' in response.data
    assert b'name="iswa_use_model_start" id="iswa-use-model-start" type="checkbox" checked' in response.data
    assert response.data.count(b"Use map time - 5 days as model start time") == 4
    assert b"busy-button" in response.data
    assert b"Grabbing and processing input data" in response.data
    assert b"Preparing run..." in response.data
    assert b"/run-progress/" in response.data
    assert b"Configuration changed. Run SURF again." in response.data
    assert b"Model Parameters" in response.data
    assert b"Advanced" in response.data
    assert b"Open manual CME editor" in response.data
    assert b"Remove Selected" in response.data
    assert b'id="cme-editor"' in response.data
    assert b"id=\"load-donki\"" in response.data
    assert b"Cone CME lists" in response.data
    assert b'name="grab_donki_at_run_start"' in response.data
    assert b"Grab the DONKI CMEs now" in response.data
    assert b"Load a user-supplied Cone CME list" in response.data
    assert b"SURF's UP" in response.data
    assert b"Space-weather Utilities for Research and Forecasting" in response.data
    assert b"Solar wind modelling via" not in response.data
    assert b"Model start date (default: 5 days prior to forecast date, to allow CME propagation)" in response.data
    assert b"Include B polarity" in response.data
    assert b"Include bpol in run" not in response.data
    assert b'name="simtime_days" type="number" step="0.1" value="10"' in response.data
    assert b'name="gamma" id="model-gamma" type="number" step="0.01" value="1.5"' in response.data
    assert b'id="edit-selected-cme"' in response.data
    assert b'name="track_cmes" type="checkbox"' in response.data
    assert b'name="track_cmes" type="checkbox" checked' not in response.data
    assert b'<option value="forecast">Forecast</option>' in response.data
    assert b'id="omni-forecast-datetime"' in response.data
    assert b'modelStartInput.addEventListener("input", syncOmniForecastTime)' in response.data
    assert response.data.count(b"syncOmniForecastTime();") >= 4
    assert b"Reconstruction (requires 27 days of data after run end time)" in response.data
    assert b"Cone CME lists (typically for model inner boundary at 0.1 AU)" in response.data
    assert b"Configure, run and explore SURF simulations" not in response.data
    assert b'name="wsa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="iswa_speed_reduction" type="checkbox" checked' in response.data
    assert b'name="mas_use_map_time"' in response.data
    assert b'name="wsa_use_map_time"' in response.data
    assert b'name="cortom_use_map_time"' in response.data
    assert b'id="model-gamma-row"' in response.data
    assert b'const modelGammaInput = document.getElementById("model-gamma")' in response.data


def test_template_turns_off_donki_for_omni_outward_selection():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert "disableDonkiForOutwardOmni" in template
    assert 'source === "omni"' in template
    assert "grabDonkiAtRunStart.checked = false" in template


def test_template_uses_clearer_top_tabs_without_duplicate_panel_headings():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert ">Run from 1 AU outwards</button>" in template
    assert 'data-inner-tabs="omni-boundaries"' in template
    assert 'data-omni-source="insitu_backmapped">Backmapped boundary</button>' in template
    assert 'data-omni-source="omni">Run from 1 AU outwards</button>' in template
    assert ">Outward propagation</span>" not in template
    assert ">Model parameters</h2>" not in template
    assert ">Ambient solar wind</h2>" not in template
    assert '<h2 class="wide">CMEs</h2>' not in template
    assert '<h2 class="mt-0">Plots</h2>' not in template
    assert "These products remain available while this server process retains the run." not in template
    assert '<h2 class="mt-0">Movies</h2>' not in template
    assert "text-base font-semibold" in template
    assert "hover:border-cyan-200" in template


def test_csv_export_prompts_for_filename_without_output_box():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'id="timeseries-csv-output"' not in template
    assert 'id="clear-timeseries-csv"' not in template
    assert 'window.prompt("CSV filename"' in template
    assert "link.download = filename" in template


def test_omni_outwards_boundary_checkbox_is_off_by_default():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'name="use_215_inner_boundary" type="checkbox"' in template
    assert 'name="use_215_inner_boundary" type="checkbox" checked' not in template
    assert "Set model inner boundary to 215 Rs" in template


def test_ambient_previews_accumulate_in_outputs():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'id="ambient-plot-history"' not in template
    assert template.count('id="plot-history"') == 1
    assert "addAmbientOutput(entry);" in template
    assert "addPlotOutput(entry, prepend);" in template
    assert "outputs.figures = [entry," in template
    assert "filename: `SURF_${source}_ambient_" in template


def test_model_defaults_to_1d_and_full_longitude_range():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'name="is_1d" id="model-is-1d" type="checkbox" checked' in template
    assert 'name="lon_min" type="number" value="0"' in template
    assert 'name="lon_max" type="number" value="360"' in template


def test_user_specified_sources_are_subtabs():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'data-inner-tabs="user-boundaries"' in template
    assert 'data-user-source="wsa">WSA</button>' in template
    assert 'data-user-source="cortom">CorTom</button>' in template
    assert 'data-user-source="user_specified">Line method</button>' in template


def test_ambient_source_radii_are_editable_with_existing_defaults():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'name="mas_source_radius_rs" type="number" min="1" step="0.1" value="30"' in template
    assert 'name="iswa_source_radius_rs" type="number" min="1" step="0.1" value="21.5"' in template
    assert 'name="wsa_source_radius_rs" type="number" min="1" step="0.1" value="21.5"' in template
    assert 'name="cortom_source_radius_rs" type="number" min="1" step="0.1" value="8"' in template


def test_timeseries_is_default_plot_product_and_omni_is_earth_only():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'class="inner-tab-button active" data-inner-tab="timeseries-product"' in template
    assert 'class="product-panel active wide" data-inner-panel="timeseries-product"' in template
    assert 'id="timeseries-plot-omni" type="checkbox" checked' in template
    assert 'plot_omni: document.getElementById("timeseries-plot-omni").checked' in template
    assert 'timeseriesObserver.value === "Earth"' in template
    assert 'sa.plot_earth_timeseries(model, plot_omni=True)' in template
    assert 'sa.plot_earth_timeseries(model, plot_omni=False)' in template
    assert 'OMNI may be unavailable for the requested dates.' in template


def test_template_hides_post_run_tabs_when_run_becomes_stale():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert "function hidePostRunTabs()" in template
    assert '["plots", "movies"].forEach' in template
    assert 'document.querySelector(`[data-tab="${name}"]`)?.classList.add("hidden")' in template
    assert 'document.getElementById("post-run-tab-spacer")?.classList.add("hidden")' in template
    assert 'if (["plots", "movies"].includes(activeTab))' in template
    assert 'activateTab("model")' in template
    assert "hidePostRunTabs();" in template
    assert 'event.submitter.textContent = "Preparing run..."' in template
    assert 'event.submitter.textContent = "Running SURF..."' in template
    assert 'if (progress.message === "Running SURF")' in template
    assert 'window.setTimeout(() => {\n          if (latestRunProgress === "Grabbing and processing input data")' not in template
    assert "function resetGeneratedCodeForCurrentState()" in template
    assert "plotCodeHistory.length = 0;" in template
    assert 'generatedCodePre.textContent = "";' in template
    assert "resetGeneratedCodeForCurrentState();" in template
    invalidation = template[
        template.index("function invalidateCompletedRun()"):
        template.index('runForm.addEventListener("input", invalidateCompletedRun)')
    ]
    assert "if (grabDonkiAtRunStart.checked && cmes.length)" in invalidation
    assert "cmes.splice(0, cmes.length);" in invalidation
    assert "selectedCmeIndex = -1;" in invalidation
    assert "renderCmes();" in invalidation


def test_template_keeps_outputs_tab_visible_and_marks_new_outputs():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'data-tab="outputs"' in template
    assert 'data-panel="outputs"' in template
    assert 'class="tab-button" type="button" role="tab" data-tab="outputs"' in template
    assert 'document.querySelector(`[data-tab="${name}"]`)?.classList.add("hidden")' in template
    assert '["plots", "movies"].forEach' in template
    assert '"outputs"' not in template[
        template.index("function hidePostRunTabs()"):template.index("function invalidateCompletedRun()")
    ]
    assert 'id="plot-output"' in template[
        template.index('data-panel="outputs"'):]
    assert ">Plots and movies appear here</h3>" in template
    assert "Choose an ambient source and click Plot." not in template
    assert "Choose a plot above to render it here." not in template
    assert "Movie rendering complete; newest output is shown first." not in template
    assert 'id="movie-output-panel"' not in template
    assert 'id="movie-player"' not in template
    assert "has-new-output" in template
    assert "function markOutputsTabHasNewContent()" in template
    assert 'if (name === "outputs") button.classList.remove("has-new-output")' in template
    assert "markOutputsTabHasNewContent();" in template
    assert 'const savedOutputsKey = "surfs-up-output-history"' in template
    assert "function blobToDataUrl(blob)" in template
    assert "function savePlotOutput(entry)" in template
    assert "function restoreSavedOutputs()" in template
    assert "restoreSavedOutputs();" in template
    assert "savePlotOutput(entry);" in template
    assert "downloadLink.download = entry.filename || \"SURF_plot.png\";" in template
    assert "downloadLink.textContent = \"Download\";" in template
    assert "filename: `SURF_${kind}_plot_${timestamp.toISOString().replace(/[:.]/g, \"-\")}.png`" in template
    assert 'filename: `SURF_${tag}_movie.gif`' in template
    assert "addPlotOutput(entry);" in template
    assert "saveFigureOutput(entry);" in template
    assert "URL.createObjectURL(blob)" not in template[
        template.index("function showPlot("):template.index("function downloadTimeseries(")
    ]


def test_movies_tab_is_disabled_for_completed_1d_runs():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")
    app_source = Path("surfs_up/web/app.py").read_text(encoding="utf-8")

    assert "{% if show_movies %}" in template
    assert 'data-tab="movies"' in template
    assert 'data-panel="movies"' in template
    assert '{% if not show_movies %}disabled aria-disabled="true"' in template
    assert "Movies are unavailable for 1D runs" in template
    assert 'context["show_movies"] = not bool(' in app_source
    assert 'simulation.model.get("is_1d", False)' in app_source


def test_movie_controls_follow_magnetic_boundary_availability():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")
    movies = template[
        template.index('data-panel="movies"'):template.index('data-panel="outputs"')
    ]

    assert 'id="movie-play"' not in movies
    assert 'id="movie-earth"' not in movies
    assert "Trace Earth connection (slow)" not in movies
    assert 'id="movie-hcs" type="checkbox" checked disabled' in template
    assert 'id="movie-ts-hcs" type="checkbox" checked disabled' in template
    assert "function syncMovieHcsControls(defaultToChecked = false)" in template
    assert "checkbox.disabled = !available" in template
    assert "if (!available) checkbox.checked = false" in template


def test_generated_code_dialog_has_copy_button():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'id="show-generated-code"' in template
    assert 'form="simulation-form" class="secondary-button"' not in template
    assert 'id="generated-code-dialog"' in template
    assert 'id="copy-generated-code"' in template
    assert "async function updateGeneratedCode" in template
    assert 'fetch(`{{ url_for("generated_code") }}`' in template
    assert 'runForm.addEventListener("input", scheduleGeneratedCodeUpdate)' in template
    assert "async function copyGeneratedCode()" in template
    assert "navigator.clipboard.writeText(codeText)" in template
    assert "document.execCommand(\"copy\")" in template
    assert 'copyGeneratedCodeButton.addEventListener("click", copyGeneratedCode)' in template


def test_generated_code_endpoint_reflects_current_form_state():
    client = create_app({"TESTING": True}).test_client()
    base_data = {
        "action": "preview",
        "ambient_source": "user_specified",
        "solver": "huxt",
        "rmin": "21.5",
        "latitude": "0",
        "simtime_days": "5",
        "speed_kms": "400",
        "start_datetime": "2026-07-03T12:00",
        "cr_num": "2300",
        "cr_lon_init_deg": "0",
        "lon_min": "315",
        "lon_max": "45",
        "frame": "sidereal",
    }

    first = client.post("/generated-code", data={**base_data, "rmax": "240"})
    second = client.post("/generated-code", data={**base_data, "rmax": "300"})

    assert first.status_code == 200
    assert second.status_code == 200
    assert "r_max=240.0 * u.solRad" in first.get_json()["code"]
    assert "r_max=300.0 * u.solRad" in second.get_json()["code"]


def test_generated_code_endpoint_includes_gamma_for_non_huxt_solver():
    response = create_app({"TESTING": True}).test_client().post(
        "/generated-code",
        data={
            "action": "preview",
            "ambient_source": "user_specified",
            "solver": "hydro",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "gamma": "1.42",
        },
    )

    assert response.status_code == 200
    code = response.get_json()["code"]
    assert "solver='hydro'" in code
    assert "model.set_gamma(1.42)" in code


def test_donki_preview_matches_surf_query_and_cone_defaults(monkeypatch):
    import surfs_up.web.app as web_app

    requested_urls = []
    analyses = [
        {
            "time21_5": "2026-07-04T12:00:00Z",
            "longitude": -10,
            "latitude": 2,
            "speed": 900,
            "halfAngle": 30,
        },
        {
            "time21_5": "2026-07-03T18:00:00Z",
            "longitude": 20,
            "latitude": -3,
            "speed": 700,
            "halfAngle": 25,
        },
    ]

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def read(self):
            return json.dumps(analyses).encode("utf-8")

    def fake_urlopen(url, timeout):
        requested_urls.append((url, timeout))
        return Response()

    monkeypatch.setattr(web_app, "urlopen", fake_urlopen)
    cmes = web_app._fetch_donki_cmes(datetime.datetime(2026, 7, 3, 12), 1)

    url, timeout = requested_urls[0]
    assert "mostAccurateOnly=true" in url
    assert "feature=LE" in url
    assert "catalog=ALL" in url
    assert "completeEntryOnly" not in url
    assert timeout == 30
    assert [cme["t_launch_day"] for cme in cmes] == [0.25, 1.0]
    assert cmes[1]["longitude"] == 350.0
    assert cmes[1]["width"] == 60.0
    assert cmes[1]["thickness_rs"] == 0
    assert cmes[1]["initial_height_rs"] == 21.5
    assert cmes[1]["cme_fixed_duration"] is True
    assert cmes[1]["fixed_duration_hr"] == 12
    assert cmes[1]["profile_type"] == "square"

    hydro_cmes = web_app._fetch_donki_cmes(
        datetime.datetime(2026, 7, 3, 12), 1, "hydro"
    )
    assert all(cme["profile_type"] == "sinusoidal" for cme in hydro_cmes)


def test_hydro_manual_cme_defaults_to_sinusoidal_with_unit_plasma_fractions():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")

    assert 'id="cme-density-fraction" type="number" value="1"' in template
    assert 'id="cme-temperature-fraction" type="number" value="1"' in template
    assert "document.querySelector('[name=\"solver\"]').value === \"hydro\"" in template
    assert '? "sinusoidal"' in template


def test_manual_cme_absolute_defaults_come_from_surf_constants():
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")
    app_source = Path("surfs_up/web/app.py").read_text(encoding="utf-8")

    assert 'value="{{ default_cme_density_pcc }}"' in template
    assert 'value="{{ default_cme_temperature_k }}"' in template
    assert 'surf_defaults["n_sw_21p5"]' in app_source
    assert 'surf_defaults["T_sw_21p5"]' in app_source


def test_run_start_donki_cmes_are_returned_to_populate_cme_tab(monkeypatch):
    import surfs_up.web.app as web_app

    donki_cme = {
        "longitude": 10.0,
        "latitude": 2.0,
        "speed": 900.0,
        "width": 45.0,
        "t_launch_day": 0.25,
        "t_launch_datetime": "2026-07-03 18:00:00",
        "thickness_rs": 0,
        "initial_height_rs": 21.5,
        "cme_expansion": False,
        "cme_fixed_duration": True,
        "fixed_duration_hr": 12,
        "profile_type": "square",
        "plasma_mode": "Fraction of ambient",
        "density_fraction": 1,
        "temperature_fraction": 1,
        "cme_density_pcc": 100,
        "cme_temperature_k": 100000,
        "source": "donki",
        "donki_id": "2026-test-donki",
    }
    monkeypatch.setattr(web_app, "_fetch_donki_cmes", lambda *_args: [donki_cme])
    monkeypatch.setattr(web_app, "build_generated_code", lambda _simulation: "# code")
    monkeypatch.setattr(
        web_app,
        "run_generated_code",
        lambda *_args, **_kwargs: SimpleNamespace(
            success=True,
            model=object(),
            message="Run completed",
            output="",
        ),
    )
    monkeypatch.setattr(web_app, "_retain_model", lambda *_args: "run123")
    monkeypatch.setattr(
        web_app,
        "_model_defaults",
        lambda: {
            "default_start": "2026-07-03T12:00:00",
            "default_iswa_map_datetime": "2026-07-03T12:00",
            "default_cr_num": 2300,
            "default_cr_lon": 0.0,
            "default_latitude": 0.0,
        },
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/",
        data={
            "action": "run",
            "ambient_source": "wsa_iswa",
            "grab_donki_at_run_start": "on",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
            "cmes_json": '[{"source":"manual","longitude":0,"latitude":0,"speed":800,'
            '"width":60,"t_launch_day":0.5}]',
        },
    )

    assert response.status_code == 200
    assert b"const submittedCmes =" in response.data
    assert b"2026-test-donki" in response.data
    assert b"Loaded ${submittedCmes.filter" in response.data
    template = Path("surfs_up/web/templates/index.html").read_text(encoding="utf-8")
    submitted_block = template.split("const submittedCmes =", 1)[1].split(
        'document.getElementById("save-configuration")', 1
    )[0]
    assert "grabDonkiAtRunStart.checked = false" not in submitted_block


def test_omni_outward_run_does_not_auto_fetch_donki(monkeypatch):
    import surfs_up.web.app as web_app

    def fail_fetch(*_args, **_kwargs):
        raise AssertionError("DONKI should not be fetched for OMNI outward runs")

    monkeypatch.setattr(web_app, "_fetch_donki_cmes", fail_fetch)
    app = create_app({"TESTING": True})

    with app.test_request_context(
        "/",
        method="POST",
        data={
            "action": "run",
            "ambient_source": "omni",
            "use_215_inner_boundary": "on",
            "grab_donki_at_run_start": "on",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    ):
        simulation = web_app._request_from_form()

    assert simulation.ambient["source"] == "omni"
    assert simulation.cmes == []
    assert simulation.model["grab_donki_at_run_start"] is False


def test_preview_donki_option_sets_codegen_flag_without_fetching(monkeypatch):
    import surfs_up.web.app as web_app

    def fail_fetch(*_args, **_kwargs):
        raise AssertionError("DONKI should not be fetched while generating preview code")

    monkeypatch.setattr(web_app, "_fetch_donki_cmes", fail_fetch)
    app = create_app({"TESTING": True})

    with app.test_request_context(
        "/",
        method="POST",
        data={
            "action": "preview",
            "ambient_source": "wsa_iswa",
            "grab_donki_at_run_start": "on",
            "solver": "huxt",
            "rmin": "21.5",
            "rmax": "240",
            "latitude": "0",
            "simtime_days": "5",
            "speed_kms": "400",
            "start_datetime": "2026-07-03T12:00",
            "cr_num": "2300",
            "cr_lon_init_deg": "0",
            "lon_min": "315",
            "lon_max": "45",
            "frame": "sidereal",
        },
    ):
        simulation = web_app._request_from_form()

    assert simulation.model["grab_donki_at_run_start"] is True
    assert simulation.cmes == []


def test_model_coordinate_endpoint_returns_synchronised_values():
    response = create_app({"TESTING": True}).test_client().get(
        "/model-coordinates?datetime=2026-07-03T12:00:00"
    )

    assert response.status_code == 200
    payload = response.get_json()
    assert payload["datetime"] == "2026-07-03T12:00:00"
    assert isinstance(payload["cr_num"], int)
    assert -90 <= payload["earth_latitude"] <= 90


def test_ambient_file_time_endpoint_returns_inferred_timestamp(monkeypatch):
    import surfs_up.web.app as web_app

    expected = datetime.datetime(2026, 7, 3, 12, 0, 0)
    monkeypatch.setattr(web_app, "_ambient_file_start_time", lambda source, path: expected)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-file-time",
        data={
            "source": "wsa",
            "file": (BytesIO(b"test data"), "sample.fits"),
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.get_json()["datetime"] == "2026-07-03T12:00:00"


@pytest.mark.parametrize(
    "source,data,filename",
    [
        (
            "mas",
            {
                "ambient_source": "mas",
                "latitude": "0",
                "mas_cr_num": "2000",
                "mas_decelerate": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "wsa",
            {
                "ambient_source": "wsa",
                "latitude": "0",
                "wsa_decelerate": "on",
                "wsa_speed_reduction": "on",
                "include_bpol": "on",
            },
            "sample.fits",
        ),
        (
            "wsa_iswa",
            {
                "ambient_source": "wsa_iswa",
                "latitude": "0",
                "iswa_map_date": "2026-07-03T12:30:00",
                "iswa_decelerate": "on",
                "iswa_speed_reduction": "on",
                "include_bpol": "on",
            },
            None,
        ),
        (
            "cortom",
            {
                "ambient_source": "cortom",
                "latitude": "0",
                "cortom_decelerate": "on",
                "include_bpol": "on",
            },
            "sample.dat",
        ),
    ],
)
def test_ambient_preview_endpoint_returns_png_for_requested_sources(monkeypatch, tmp_path, source, data, filename):
    import surf.surf_inputs as sin

    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s
    b_profile = np.linspace(1, 4, 4)

    monkeypatch.setattr(sin, "get_MAS_vr_map", lambda cr_num: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_MAS_long_profile", lambda cr_num, latitude: profile)
    monkeypatch.setattr(sin, "get_MAS_br_long_profile", lambda cr_num, latitude: b_profile)
    monkeypatch.setattr(
        sin,
        "map_v_boundary_inwards",
        lambda v_orig, source_radius, inner_radius, b_orig=None, **kwargs: (
            (v_orig * 0.8, np.asarray(b_orig) * 0.7) if b_orig is not None else v_orig * 0.8
        ),
    )
    monkeypatch.setattr(
        sin,
        "map_v_inwards",
        lambda v_orig, source_radius, longitude, inner_radius: (v_orig * 0.9, None, None, None),
    )
    monkeypatch.setattr(
        sin,
        "get_WSA_maps",
        lambda path: (speed_map, longitudes, latitudes),
    )
    monkeypatch.setattr(sin, "get_WSA_long_profile", lambda path, latitude: profile)
    monkeypatch.setattr(sin, "get_WSA_br_long_profile", lambda path, latitude: b_profile)
    monkeypatch.setattr(sin, "get_WSA_from_ISWA", lambda required_for: str(tmp_path / "iswa.fits"))
    monkeypatch.setattr(sin, "get_CorTom_vr_map", lambda path: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_CorTom_long_profile", lambda path, latitude: profile)

    if source == "wsa_iswa":
        (tmp_path / "iswa.fits").write_bytes(b"fits")

    request_data = dict(data)
    if filename is not None:
        request_data[f"{source}_file"] = (BytesIO(b"test data"), filename)

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data=request_data,
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert response.mimetype == "image/png"


def test_ambient_preview_uses_parker_wsa_reduction_for_non_huxt(monkeypatch):
    import surf.surf_inputs as sin

    calls = []
    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s

    monkeypatch.setattr(sin, "get_WSA_maps", lambda path: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_WSA_long_profile", lambda path, latitude: profile)
    monkeypatch.setattr(sin, "get_WSA_br_long_profile", lambda path, latitude: np.ones(4))
    monkeypatch.setattr(sin, "map_v_boundary_inwards", lambda v_orig, *args, **kwargs: v_orig)
    monkeypatch.setattr(
        sin,
        "map_v_inwards",
        lambda v_orig, source_radius, longitude, inner_radius: calls.append("huxt") or (v_orig, None, None, None),
    )
    monkeypatch.setattr(
        sin,
        "map_v_inwards_parker",
        lambda v_orig, source_radius, longitude, inner_radius: calls.append("parker") or (v_orig, None, None, None),
        raising=False,
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data={
            "solver": "hydro",
            "ambient_source": "wsa",
            "latitude": "0",
            "wsa_decelerate": "on",
            "wsa_speed_reduction": "on",
            "wsa_file": (BytesIO(b"test data"), "sample.fits"),
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert calls == ["parker"]


def test_ambient_preview_passes_parker_acc_profile_for_non_huxt_boundary_mapping(monkeypatch):
    import surf.surf_inputs as sin

    acc_profiles = []
    speed_map = np.arange(12, dtype=float).reshape(3, 4) * u.km / u.s
    longitudes = np.linspace(0, 360, 4, endpoint=False) * u.deg
    latitudes = np.linspace(-30, 30, 3) * u.deg
    profile = np.linspace(300, 500, 4) * u.km / u.s

    monkeypatch.setattr(sin, "get_MAS_vr_map", lambda cr_num: (speed_map, longitudes, latitudes))
    monkeypatch.setattr(sin, "get_MAS_long_profile", lambda cr_num, latitude: profile)
    monkeypatch.setattr(
        sin,
        "map_v_boundary_inwards",
        lambda v_orig, *args, **kwargs: acc_profiles.append(kwargs.get("acc_profile")) or v_orig,
    )

    response = create_app({"TESTING": True}).test_client().post(
        "/ambient-plot.png",
        data={
            "solver": "hydro",
            "ambient_source": "mas",
            "latitude": "0",
            "mas_cr_num": "2000",
            "mas_decelerate": "on",
        },
        content_type="multipart/form-data",
    )

    assert response.status_code == 200
    assert acc_profiles == ["parker"]
