"""Code generation helpers shared by user interfaces."""

from __future__ import annotations

from .models import SimulationRequest


def _omni_icme_list(state: dict, ambient: dict) -> str | None:
    """Return the selected ICME catalogue, including a date-based legacy default."""
    if "icme_list" in ambient:
        value = ambient["icme_list"]
        # SURF accepts the literal string "None" to bypass ICME removal.  Use
        # it consistently because some released versions do not handle the
        # Python ``None`` value correctly.
        return "None" if value in {None, "None", ""} else str(value)
    year = int(str(state["start_datetime"])[:4])
    return "DONKI" if year >= 2026 else "CaneRichardson"


def _raw_omni_gap_fill_lines(start: str, end: str) -> list[str]:
    """Download raw OMNI and fill ordinary gaps without removing ICME intervals."""
    return [
        f"omni_input = sinsit.get_omni({start}, {end})",
        "omni_numeric = omni_input.select_dtypes(include='number').columns",
        "omni_input[omni_numeric] = omni_input[omni_numeric].interpolate(",
        "    method='linear', limit_direction='both'",
        ")",
    ]


def build_uniform_boundary_code(request: SimulationRequest) -> str:
    """Build a SURF script for the portable, user-specified boundary workflow."""
    request.validate()
    state = request.model
    ambient = request.ambient
    if ambient["source"] != "user_specified":
        raise ValueError("The web interface currently supports user-specified boundaries.")

    profile = ambient.get("speed_profile_kms", [400.0] * 128)
    if not profile:
        raise ValueError("The speed profile cannot be empty.")
    solver = str(state["solver"]).lower()

    lines = [
        "import datetime",
        "import numpy as np",
        "import astropy.units as u",
        "import surf.surf as s",
        "",
        "# Generated by SURFs_UP shared core",
        "# Define the ambient inner-boundary speed profile and run start time.",
        f"v_boundary = np.array({list(profile)!r}) * (u.km / u.s)",
        f"start_time = datetime.datetime.fromisoformat({state['start_datetime']!r})",
        "",
        "# Configure the model domain, grid, coordinates, and solver.",
        "model = s.SURF(",
        "    v_boundary=v_boundary,",
        f"    cr_num={int(state['cr_num'])},",
        f"    cr_lon_init={float(state['cr_lon_init_deg'])} * u.deg,",
        f"    r_min={float(state['rmin'])} * u.solRad,",
        f"    r_max={float(state['rmax'])} * u.solRad,",
        f"    dr={float(state.get('dr_rs', 1.5))} * u.solRad,",
        f"    nlon={int(state.get('nlon', 128))},",
        f"    v_max={float(state.get('vmax_kms', 3000.0))} * (u.km/u.s),",
    ]
    if state.get("is_1d", False):
        lines.append("    lon_out=0.0 * u.deg,")
    else:
        lines.extend(
            [
                f"    lon_start={float(state.get('lon_min', 0.0))} * u.deg,",
                f"    lon_stop={float(state.get('lon_max', 360.0))} * u.deg,",
            ]
        )
    lines.extend(
        [
            f"    latitude={float(state['latitude'])} * u.deg,",
            f"    frame={state.get('frame', 'sidereal')!r},",
            f"    simtime={float(state['simtime_days'])} * u.day,",
        f"    solver={solver!r},",
        "    dt_scale=4,",
        f"    track_cmes={bool(state.get('track_cmes', False))},",
        ")",
        ]
    )
    if solver != "huxt":
        lines.extend([f"model.set_gamma({float(state.get('gamma', 1.5))})", ""])
    else:
        lines.append("")
    lines.extend(
        [
            "# Solve the ambient model without any CMEs.",
            "model.solve([])",
            "",
        ]
    )
    return "\n".join(lines)


def _wsa_speed_reduction_lines() -> list[str]:
    return [
        "wsa_lon = np.linspace(0, 2*np.pi, len(v_boundary), endpoint=False)*u.rad",
        "if solver == 'huxt':",
        "    wsa_reduction = sin.map_v_inwards(",
        "        v_boundary, 215*u.solRad, wsa_lon, rmin",
        "    )",
        "else:",
        "    wsa_reduction = sin.map_v_inwards_parker(",
        "        v_boundary, 215*u.solRad, wsa_lon, rmin, gamma=gamma",
        "    )",
        "v_boundary = wsa_reduction[0]",
    ]


def build_generated_code(request: SimulationRequest) -> str:
    """Build runnable code for the workflows exposed by both interfaces.

    The compact uniform workflow remains separate because it produces especially
    readable preview code. Other sources and CMEs use the general builder below.
    """
    request.validate()
    state, ambient, cmes = request.model, request.ambient, request.cmes
    solver = str(state["solver"]).lower()
    omni_icme_list = _omni_icme_list(state, ambient)
    gamma = float(state.get("gamma", 1.5))
    if (
        ambient["source"] == "user_specified"
        and not cmes
        and not state.get("grab_donki_at_run_start")
        and not state.get("streak_lines_enabled")
        and not state.get("include_bpol")
    ):
        return build_uniform_boundary_code(request)

    lines = [
        "import datetime",
        "import numpy as np",
        "import astropy.units as u",
        "import astropy.constants as const",
        "import surf.surf as s",
        "import surf.surf_inputs as sin",
        "",
        "# Define settings shared by the boundary preparation and model setup.",
        f"solver = {solver!r}",
        "acc_profile = 'huxt' if solver == 'huxt' else 'parker'",
        f"rmin = {float(state['rmin'])} * u.solRad",
        f"rmax = {float(state['rmax'])} * u.solRad",
        f"latitude = {float(state['latitude'])} * u.deg",
        f"simtime = {float(state['simtime_days'])} * u.day",
        f"start_time = datetime.datetime.fromisoformat({state['start_datetime']!r})",
        "",
        "# Prepare the selected ambient solar-wind boundary.",
    ]
    if solver != "huxt":
        lines.insert(-2, f"gamma = {gamma}")
    source = ambient["source"]
    include_bpol = bool(state.get("include_bpol"))
    if source == "user_specified":
        if include_bpol:
            raise ValueError(
                "A magnetic boundary is not available for a user-specified speed profile."
            )
        lines.append(
            f"v_boundary = np.array({ambient['speed_profile_kms']!r}) * (u.km/u.s)"
        )
    elif source == "mas":
        source_radius_rs = float(ambient.get("source_radius_rs", 30.0))
        lines.append(f"v_boundary = sin.get_MAS_long_profile({ambient['cr_num']}, latitude)")
        if include_bpol:
            lines.append(f"b_boundary = sin.get_MAS_br_long_profile({ambient['cr_num']}, latitude)")
            lines.extend(
                [
                    "if len(b_boundary) != len(v_boundary):",
                    "    b_lon = np.linspace(0, 360, len(b_boundary), endpoint=False)",
                    "    v_lon = np.linspace(0, 360, len(v_boundary), endpoint=False)",
                    "    b_boundary = np.interp(v_lon, b_lon, np.asarray(b_boundary), period=360)",
                ]
            )
        if ambient.get("decelerate_to_inner_boundary", True):
            call = f"sin.map_v_boundary_inwards(v_boundary, {source_radius_rs}*u.solRad, rmin, acc_profile=acc_profile"
            call += ", gamma=gamma" if solver != "huxt" else ""
            call += ", b_orig=b_boundary)" if include_bpol else ")"
            lines.append(("v_boundary, b_boundary = " if include_bpol else "v_boundary = ") + call)
    elif source == "wsa":
        source_radius_rs = float(ambient.get("source_radius_rs", 21.5))
        lines.append(
            f"v_boundary = sin.get_WSA_long_profile(r{ambient['filepath']!r}, latitude)"
        )
        if include_bpol:
            lines.append(
                f"b_boundary = sin.get_WSA_br_long_profile(r{ambient['filepath']!r}, latitude)"
            )
        if ambient.get("apply_wsa_speed_reduction", False):
            lines.extend(_wsa_speed_reduction_lines())
        if ambient.get("decelerate_to_inner_boundary", True):
            call = f"sin.map_v_boundary_inwards(v_boundary, {source_radius_rs}*u.solRad, rmin, acc_profile=acc_profile"
            call += ", gamma=gamma" if solver != "huxt" else ""
            call += ", b_orig=b_boundary)" if include_bpol else ")"
            lhs = "v_boundary, b_boundary = " if include_bpol else "v_boundary = "
            lines.append(lhs + call)
    elif source == "wsa_iswa":
        source_radius_rs = float(ambient.get("source_radius_rs", 21.5))
        map_datetime = ambient.get("iswa_map_datetime", state["start_datetime"])
        lines.append(
            f"iswa_map_time = datetime.datetime.fromisoformat({map_datetime!r})"
        )
        lines.append("wsa_path = sin.get_WSA_from_ISWA(iswa_map_time)")
        lines.append("v_boundary = sin.get_WSA_long_profile(wsa_path, latitude)")
        if include_bpol:
            lines.append("b_boundary = sin.get_WSA_br_long_profile(wsa_path, latitude)")
        if ambient.get("apply_wsa_speed_reduction", False):
            lines.extend(_wsa_speed_reduction_lines())
        if ambient.get("decelerate_to_inner_boundary", True):
            call = f"sin.map_v_boundary_inwards(v_boundary, {source_radius_rs}*u.solRad, rmin, acc_profile=acc_profile"
            call += ", gamma=gamma" if solver != "huxt" else ""
            call += ", b_orig=b_boundary)" if include_bpol else ")"
            lhs = "v_boundary, b_boundary = " if include_bpol else "v_boundary = "
            lines.append(lhs + call)
    elif source == "cortom":
        source_radius_rs = float(ambient.get("source_radius_rs", 8.0))
        lines.append(
            f"v_boundary = sin.get_CorTom_long_profile(r{ambient['filepath']!r}, latitude)"
        )
        if ambient.get("decelerate_to_inner_boundary", True):
            gamma_arg = ", gamma=gamma" if solver != "huxt" else ""
            lines.append(
                "v_boundary = sin.map_v_boundary_inwards("
                f"v_boundary, {source_radius_rs}*u.solRad, rmin, acc_profile=acc_profile{gamma_arg})"
            )
    elif source in {"insitu_backmapped", "omni"}:
        lines.insert(6, "import surf.surf_insitu as sinsit")
        if source == "insitu_backmapped":
            fn = (
                "omniSURF_reconstruction"
                if ambient.get("mode") == "reconstruction"
                else "omniSURF_forecast"
            )
            forecast_datetime = ambient.get("forecast_datetime")
            forecast_time = (
                f"datetime.datetime.fromisoformat({forecast_datetime!r})"
                if forecast_datetime
                else "start_time + datetime.timedelta(days=5)"
            )
            if fn.endswith("reconstruction"):
                call_start = "start_time"
                second = "start_time + datetime.timedelta(days=simtime.to_value(u.day))"
                raw_omni_start = "start_time - datetime.timedelta(days=28)"
                raw_omni_end = "start_time + datetime.timedelta(days=simtime.to_value(u.day) + 28)"
            else:
                call_start = forecast_time
                second = "simtime=simtime, buffertime=5*u.day"
                raw_omni_start = f"{forecast_time} - datetime.timedelta(days=28)"
                raw_omni_end = f"{forecast_time} + datetime.timedelta(days=28)"
            longitude_args = ""
            if not state.get("is_1d", False):
                longitude_args = (
                    f", lon_start={float(state.get('lon_min', 0))}*u.deg, "
                    f"lon_stop={float(state.get('lon_max', 360))}*u.deg"
                )
            if omni_icme_list == "None":
                lines.extend(_raw_omni_gap_fill_lines(raw_omni_start, raw_omni_end))
            omni_input_arg = ", omni_input=omni_input" if omni_icme_list == "None" else ""
            lines.extend(
                [
                    f"model = sinsit.{fn}({call_start}, {second}, rmin=rmin, rmax=rmax, "
                    f"dr={float(state.get('dr_rs', 1.5))}*u.solRad, "
                    f"nlon={int(state.get('nlon', 128))}, "
                    f"v_max={float(state.get('vmax_kms', 3000.0))}*(u.km/u.s), "
                    f"dt_scale=4, solver=solver, run_2d={not state.get('is_1d', False)}, "
                    f"track_cmes={bool(state.get('track_cmes', False))}, "
                    f"include_b_boundary={include_bpol}"
                    f", icme_list={omni_icme_list!r}"
                    f"{omni_input_arg}"
                    f"{longitude_args})"
                ]
            )
        else:
            omni_rmin = "215*u.solRad" if ambient.get("use_215_inner_boundary", True) else "rmin"
            geometry = (
                ", lon_out=0*u.deg"
                if state.get("is_1d")
                else (
                    f", frame={state.get('frame', 'sidereal')!r}"
                    f", lon_start={float(state.get('lon_min', 0))}*u.deg"
                    f", lon_stop={float(state.get('lon_max', 360))}*u.deg"
                )
            )
            lines.append(
                "end_time = start_time + datetime.timedelta(days=simtime.to_value(u.day))"
            )
            if omni_icme_list == "None":
                lines.extend(
                    _raw_omni_gap_fill_lines(
                        "start_time - datetime.timedelta(days=28)",
                        "end_time + datetime.timedelta(days=28)",
                    )
                )
            if ambient.get("use_215_inner_boundary", True):
                longitude_args = ""
                omni_input_arg = (
                    ", omni_input=omni_input" if omni_icme_list == "None" else ""
                )
                if not state.get("is_1d", False):
                    longitude_args = (
                        f", lon_start={float(state.get('lon_min', 0))}*u.deg"
                        f", lon_stop={float(state.get('lon_max', 360))}*u.deg"
                    )
                lines.append(
                    "model = sinsit.omniSURF_1au_out("
                    "start_time, end_time, rmax=rmax, "
                    f"dr={float(state.get('dr_rs', 1.5))}*u.solRad, "
                    f"nlon={int(state.get('nlon', 128))}, "
                    f"v_max={float(state.get('vmax_kms', 3000.0))}*(u.km/u.s), "
                    f"dt_scale=4, solver=solver, run_2d={not state.get('is_1d', False)}, "
                    f"track_cmes={bool(state.get('track_cmes', False))}, "
                    f"include_b_boundary={include_bpol}"
                    f", icme_list={omni_icme_list!r}"
                    f"{omni_input_arg}"
                    f"{longitude_args})"
                )
            else:
                lines.extend(
                    [
                    "time_grid, vcarr, bcarr = sinsit.generate_vCarr_from_OMNI(start_time, end_time)",
                    "model = sin.set_time_dependent_boundary("
                    f"vcarr, time_grid, start_time, simtime, r_min={omni_rmin}, r_max=rmax, "
                    f"dr={float(state.get('dr_rs', 1.5))}*u.solRad, "
                    f"nlon={int(state.get('nlon', 128))}, "
                    f"v_max={float(state.get('vmax_kms', 3000.0))}*(u.km/u.s), "
                    "dt_scale=4, latitude=latitude, solver=solver, "
                    f"track_cmes={bool(state.get('track_cmes', False))}"
                    + geometry
                    + (", bgrid_Carr=bcarr" if include_bpol else "")
                    + ")",
                    ]
                )
    else:
        raise ValueError(f"Unsupported ambient source: {source}")

    if source not in {"insitu_backmapped", "omni"}:
        lines.extend(
            [
                "",
                "# Configure the SURF model using the prepared boundary.",
            ]
        )
        args = [
            "v_boundary=v_boundary",
            f"cr_num={int(state['cr_num'])}",
            f"cr_lon_init={float(state['cr_lon_init_deg'])}*u.deg",
            "r_min=rmin",
            "r_max=rmax",
            f"dr={float(state.get('dr_rs', 1.5))}*u.solRad",
            f"nlon={int(state.get('nlon', 128))}",
            f"v_max={float(state.get('vmax_kms', 3000.0))}*(u.km/u.s)",
            "latitude=latitude",
            f"frame={state.get('frame', 'sidereal')!r}",
            "simtime=simtime",
            "dt_scale=4",
            "solver=solver",
            f"track_cmes={bool(state.get('track_cmes', False))}",
        ]
        if include_bpol and source in {"mas", "wsa", "wsa_iswa"}:
            args.insert(1, "b_boundary=b_boundary")
        if state.get("is_1d"):
            args.append("lon_out=0*u.deg")
        else:
            args.extend(
                [
                    f"lon_start={float(state.get('lon_min', 0))}*u.deg",
                    f"lon_stop={float(state.get('lon_max', 360))}*u.deg",
                ]
            )
        lines.append("model = s.SURF(" + ", ".join(args) + ")")

    if solver != "huxt":
        lines.extend(["", "model.set_gamma(gamma)"])

    lines.extend(
        [
            "",
            "# Build the list of cone CMEs injected into the simulation.",
        ]
    )
    lines.append("cme_list = []")
    if state.get("grab_donki_at_run_start"):
        lines.extend(
            [
                "donki_end_time = start_time + datetime.timedelta(days=simtime.to_value(u.day))",
                "donki_cmes = sin.get_DONKI_cme_list(model, start_time, donki_end_time)",
                "if solver == 'hydro':",
                "    for donki_cme in donki_cmes:",
                "        donki_cme.profile_type = 'sinusoidal'",
                "cme_list.extend(donki_cmes)",
            ]
        )
    literal_cmes = [
        cme
        for cme in cmes
        if not (state.get("grab_donki_at_run_start") and cme.get("source") == "donki")
    ]
    for index, cme in enumerate(literal_cmes):
        plasma = (
            [
                f"cme_density=({float(cme['cme_density_pcc'])}/u.cm**3*const.m_p).to(u.kg/u.m**3)",
                f"cme_temperature={float(cme['cme_temperature_k'])}*u.K",
            ]
            if cme.get("plasma_mode") == "Absolute values"
            else [
                f"density_fraction={float(cme.get('density_fraction', 1))}",
                f"temperature_fraction={float(cme.get('temperature_fraction', 1))}",
            ]
        )
        args = [
            f"t_launch={float(cme['t_launch_day'])}*u.day",
            f"longitude={float(cme['longitude'])}*u.deg",
            f"latitude={float(cme['latitude'])}*u.deg",
            f"width={float(cme['width'])}*u.deg",
            f"v={float(cme['speed'])}*u.km/u.s",
            f"thickness={float(cme.get('thickness_rs', 0))}*u.solRad",
            f"initial_height={float(cme.get('initial_height_rs', state['rmin']))}*u.solRad",
            f"cme_expansion={bool(cme.get('cme_expansion'))}",
            f"cme_fixed_duration={bool(cme.get('cme_fixed_duration', True))}",
            f"fixed_duration={float(cme.get('fixed_duration_hr', 12))}*u.hour",
            *plasma,
            f"profile_type={cme.get('profile_type', 'square')!r}",
        ]
        lines.extend(
            [f"cme_{index} = s.ConeCME(" + ", ".join(args) + ")", f"cme_list.append(cme_{index})"]
        )
    spacing = float(state.get("streak_spacing_deg", 10))
    streak = f"np.arange(0, 360, {spacing})*u.deg" if state.get("streak_lines_enabled") else "np.array([])*u.deg"
    lines.extend(
        [
            "",
            "# Evolve the model with the configured CMEs and optional streak lines.",
        ]
    )
    lines.append(f"model.solve(cme_list, streak_carr={streak})")
    return "\n".join(lines) + "\n"
